version: '3'
services:
  mysql:
    # Schema is created by Alembic migrations when the flask container starts.
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    container_name: a_mysql
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 50s
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    container_name: a_flask
    env_file:
      - .env
    restart: always
    image: ${ECR_ACCOUNT}/motivetag:flask
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
    container_name: a_nginx
    restart: always
    image: ${ECR_ACCOUNT}/motivetag:nginx