#For ECS
# upstream backend {
#   server 127.0.0.1:3000;
# }

# For VM(docker-compose)
upstream backend {
  server a_flask:3000;
}

# upstream backend_other {
#   server 0.0.0.0:3001;
# }

upstream jenkins {
  server 0.0.0.0:8080;
}

server {
  listen 80;
  listen [::]:80;
  listen 443 ssl;
  server_name motivetag.com *.motivetag.com;
  ssl_certificate     /etc/ssl/motivetag.com/motivetag.com.pem;
  ssl_certificate_key /etc/ssl/motivetag.com/motivetag.com.key;
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;
  client_max_body_size 5m;
  location ~* / {
    proxy_pass http://backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location ~* /healthcheck {
    return 200 'healthy\n';
  }
}

server{
  listen 443 ssl;
  server_name jenkins.motivetag.com;
  ssl_certificate     /etc/ssl/motivetag.com/motivetag.com.pem;
  ssl_certificate_key /etc/ssl/motivetag.com/motivetag.com.key;
  location ~* / {
    proxy_pass http://jenkins;
  }
}

